spring:
  application:
    name: restauranteapi
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurantdb
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: ${JWT_SECRET:05b0f768-fe7b-49aa-b934-44ef29634de3}